import 'package:bloc/bloc.dart';
import 'package:weatherapp/models/weathermodels.dart';
import 'package:weatherapp/network/network.dart';

class WeatherCubit extends Cubit<Autogenerated> {
  WeatherCubit(Autogenerated initialState) : super(initialState);
  void get(String city) {
    Network network = Network();
    Future<Autogenerated> futureWeather =
        network.getWeatherForecast(cityName: city);
    try {
      futureWeather.then((value) => emit(value));
    } catch (e) {
      print(e.toString());
    }
  }
}
