/*import 'package:bloc/bloc.dart';
import 'package:equatable/equatable.dart';
import 'package:weatherapp/models/weathermodels.dart';
import 'package:weatherapp/network/network.dart';

part 'weather_state.dart';

class WeatherCubit extends Cubit<WeatherState> {
  WeatherCubit() : super(WeatherInitial());
  void get(String city) {
    final Network network = Network();
    Future<Autogenerated> futureWeather =
        network.getWeatherForecast(cityName: city);
    try {
      futureWeather.then((value) => emit(value));
    } catch (e) {
      print(e.toString());
    }
  }
}*/
