import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:weatherapp/models/weathermodels.dart';

class Network {
  Future<Autogenerated> getWeatherForecast({required String cityName}) async {
    String apikey = "e03fd7355fe0464c906ec6c3c4c1ed59";
    var url = "https://api.openweathermap.org/data/2.5/forecast?q=" +
        cityName +
        "&cnt=7&units=metric" +
        "&appid=" +
        apikey;
    final response = await http.get(Uri.parse(url
        // "http://api.openweathermap.org/data/2.5/forecast?q=montpEllier&appid=e03fd7355fe0464c906ec6c3c4c1ed59"
        ));
    if (response.statusCode == 200) {
      return Autogenerated.fromJson(json.decode(response.body));
    } else {
      throw Exception("Error getting weather forecast");
    }
  }
}
